/// Build script: filter `typst_assets::fonts()` down to the fonts actually
/// needed by the problem set (currently New Computer Modern Math) and write
/// only those bytes to `$OUT_DIR`. `lib.rs` includes the generated `fonts.rs`
/// which embeds those bytes via `include_bytes!` — so the WASM binary never
/// contains the unused font families.
///
/// To add support for new font families (e.g. if Markup problems are added
/// that need a text font), extend the `KEEP` slice below.
use std::fmt::Write as _;

use typst::foundations::Bytes;
use typst::text::Font;

const KEEP: &[&str] = &["New Computer Modern Math"];

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");

    let mut includes = String::new();
    let mut seen = std::collections::HashSet::new();

    for (i, bytes) in typst_assets::fonts().enumerate() {
        let Some(family) = Font::iter(Bytes::new(bytes))
            .next()
            .map(|f| f.info().family.clone())
        else {
            continue;
        };

        if !KEEP.contains(&family.as_str()) || seen.contains(&i) {
            continue;
        }
        seen.insert(i);

        let path = format!("{out_dir}/font_{i}.bin");
        std::fs::write(&path, bytes).expect("write font");
        // Rust string-escapes the path so it's safe in the generated source.
        writeln!(includes, "    include_bytes!({path:?}),").expect("write to String");
    }

    let code = format!(
        "// Generated by build.rs — do not edit.\n\
         const BUNDLED_FONTS: &[&[u8]] = &[\n\
         {includes}\
         ];\n"
    );
    std::fs::write(format!("{out_dir}/fonts.rs"), code).expect("write fonts.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
